ARG FROM_IMAGE_NAME=nvcr.io/nvidia/pytorch:24.01-py3
FROM ${FROM_IMAGE_NAME}

# apt dependencies
RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y ffmpeg libsm6 libxext6

# Remove the opencv version shipped with the base image
# https://github.com/opencv/opencv-python/issues/884
RUN pip uninstall -y opencv
RUN rm -rf /usr/local/lib/python3.10/dist-packages/cv2/

# install LDM
COPY stable_diffusion/ /diffusion/
COPY scripts/run_benchmark.sh /diffusion/run_benchmark.sh

RUN pip install --no-cache-dir -r /diffusion/requirements.txt
RUN pip install pytorch_lightning
RUN pip install httpx==0.24.1

RUN git clone https://github.com/mlperf/logging.git mlperf-logging && pip install -e mlperf-logging

RUN cd /diffusion

WORKDIR /diffusion

RUN chmod +x run_benchmark.sh
CMD ["./run_benchmark.sh"]
