# Start from TensorFlow 1.15.2 GPU base image
FROM tensorflow/tensorflow:2.4.0-gpu

# Check tensorflow version
RUN python -c "import tensorflow as tf; print('Tensorflow version:', tf.__version__)"
RUN pip install mlperf_logging

ENV TF_XLA_FLAGS="--tf_xla_auto_jit=2"

WORKDIR /workspace

# Copy everything from your current directory into /workspace
COPY bert/ /workspace/bert/
COPY eval_10k /workspace/eval_10k
COPY scripts/run_benchmark.sh /workspace/run_benchmark.sh

RUN chmod +x ./run_benchmark.sh

# Default command: execute the dataset download script
CMD ["./run_benchmark.sh"]
